SELECT 
  BD.FECHA_TX AS FECHA_TX, 
  DATE_TRUNC(
    "MONTH", 
    TO_DATE(BD.FECHA_TX)
  ) AS MONTH, 
  CASE BD.CLIENT_TYPE WHEN 'LARGE' THEN 'WALLET' WHEN 'ENTERPRISE' THEN 'BANK' END AS STREAM, 
  BD.CLIENT_CODE AS CLIENT_CODE, 
  UPPER(BD.CLIENT_DESC) AS CLIENT_NAME, 
  SUM(BD.CA17_VALOR) AS GTV, 
  COUNT(BD.DOCUMENTO_USUARIO) AS TX_ABONO, 
  COUNT(
    DISTINCT(BD.DOCUMENTO_USUARIO)
  ) AS UNIQUE_USERS 
FROM 
  "COBREDB"."DATABASE_OLTP_REPORTS"."OLTP_BILLING_REPORT_DETAIL" BD 
  LEFT JOIN "COBREDB"."TEMP_TABLES"."TA17_TRANSACCIONES_PURAS" TR ON (BD.CA17_UUID = TR.CA17_UUID) 
  LEFT JOIN "COBREDB"."TEMP_TABLES"."TA10_CUENTAS" TC ON (
    TR.CA17_CA10_CUENTA_ID = TC.CA10_ID 
    AND TR.SCHEMA = TC.SCHEMA
  ) 
  LEFT JOIN "COBREDB"."TEMP_TABLES"."TA09_CLIENTES" CL ON TC.CA10_CA09_CLIENTE_ID = CL.CA09_ID 
  AND TC.SCHEMA = CL.SCHEMA 
  LEFT JOIN "COBREDB"."TEMP_TABLES"."TP01_TIPOS_DOCUMENTO" TP ON (
    CL.CA09_CP01_TIPO_DOCUMENTO_ID = TP.CP01_ID 
    AND CL.SCHEMA = TP.SCHEMA
  ) 
WHERE 
  BD.FECHA_HORA_APLICACION_TX IS NOT NULL 
  AND BD.CLIENT_CODE NOT IN ('PXT', 'DEM', 'PIC') 
  AND (
    BD.CA16_TRANSFER_STATE = 'APLICADO' 
    OR BD.CA16_TRANSFER_STATE IS NULL
  ) 
  AND BD.TIPO_TX_DESC = 'Abono' 
GROUP BY 
  FECHA_TX, 
  MONTH, 
  STREAM, 
  CLIENT_CODE, 
  CLIENT_NAME 
UNION 
SELECT 
  TO_DATE(TR.CA17_FECHA) AS FECHA_TX, 
  DATE_TRUNC(
    "MONTH", 
    TO_DATE(TR.CA17_FECHA)
  ) AS MONTH, 
  CASE WHEN EMP.NOMBRE IN (
    'CTG', 'CVA', 'CBQ', 'CAT', 'CST', 'CFM', 
    'CHU', 'CRI', 'CBY', 'CFD'
  ) THEN 'WALLET' ELSE 'BANK' END AS STREAM, 
  EMP.ALIAS AS CLIENT_CODE, 
  EMP.NOMBRE AS CLIENT_NAME, 
  SUM(TR.CA17_VALOR) AS GTV, 
  COUNT(CL.CA09_NUMERO_DOCUMENTO) AS TX_ABONO, 
  COUNT(
    DISTINCT(CL.CA09_NUMERO_DOCUMENTO)
  ) AS UNIQUE_USERS 
FROM 
  "COBREDB"."TEMP_TABLES"."TA17_TRANSACCIONES_PURAS" TR 
  INNER JOIN "COBREDB"."TEMP_TABLES"."TP06_TIPOS_TRANSACCION" TT ON (
    TR.CA17_CP06_TIPO_TRANSACCION_ID = TT.CP06_ID 
    AND TR.SCHEMA = TT.SCHEMA
  ) 
  INNER JOIN "COBREDB"."TEMP_TABLES"."TA10_CUENTAS" CU ON (
    TR.CA17_CA10_CUENTA_ID = CU.CA10_ID 
    AND TR.SCHEMA = CU.SCHEMA
  ) 
  INNER JOIN "COBREDB"."TEMP_TABLES"."TA09_CLIENTES" CL ON (
    CU.CA10_CA09_CLIENTE_ID = CL.CA09_ID 
    AND CU.SCHEMA = CL.SCHEMA
  ) 
  LEFT JOIN "COBREDB"."TEMP_TABLES"."TA08_TERMINALES" TL ON (
    TR.CA17_CA08_TERMINAL_ID = TL.CA08_ID 
    AND TR.SCHEMA = TL.SCHEMA
  ) 
  LEFT JOIN "COBREDB"."TEMP_TABLES"."TA07_SUCURSALES" SL ON (
    TL.CA08_CA07_SUCURSAL_ID = SL.CA07_ID 
    AND TL.SCHEMA = SL.SCHEMA
  ) 
  LEFT JOIN (
    WITH EMP AS (
      SELECT 
        DISTINCT CASE WHEN e.schema LIKE 'DATABASE_%_BILLETERA' THEN substr(e.schema, 10, 3) WHEN e.schema LIKE 'DATABASE_CMP1_%_BILLETERA%' THEN substr(e.schema, 39, 3) ELSE LEFT(e.CA02_NOMBRE_CORTO, 3) END ALIAS, 
        e.CA02_NOMBRE_CORTO WORKPLACEBANK_CODE, 
        en.CA01_NOMBRE NOMBRE, 
        e.schema SCHEMA_SNOWFLAKE 
      from 
        cobredb.temp_tables.TA02_EMISORES e 
        inner join cobredb.temp_tables.TA01_ENTIDADES en on e.CA02_CA01_ENTIDAD_ID = en.ca01_id 
        AND e.schema = en.schema 
      where 
        schema_snowflake <> 'DATABASE_ENT1_MX_PROD_COBRE_CO_BILLETERA_PXT_MX_PROD' --> Saco pexto de mexico
        ) 
    SELECT 
      * 
    FROM 
      EMP
  ) AS EMP ON TR.SCHEMA = EMP.SCHEMA_SNOWFLAKE 
WHERE 
  (TT.CP06_DESCRIPCION = 'Abono') 
  AND FECHA_TX < '2022-05-01' 
GROUP BY 
  FECHA_TX, 
  MONTH, 
  STREAM, 
  CLIENT_CODE, 
  CLIENT_NAME 
ORDER BY 
  FECHA_TX ASC, 
  STREAM DESC, 
  CLIENT_CODE ASC
